import "./globals.css"
import { Barlow } from 'next/font/google';
import Cursor from "./components/Cursor";
import Navbar1 from "./components/Navbar/Navbar1";
import { GlobalContextProvider} from "@/context/GlobalContext";
import Sweep from "./components/Sweep";

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // include only what you need
  variable: '--font-barlow',           // optional, for CSS variable support
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html className="dark" lang="en">
      <GlobalContextProvider>
        <body className={`dark ${barlow?.variable}`}>
          {/* <Sweep/> */}
          <Navbar1 />
          {children}
          <Cursor />
        </body>
      </GlobalContextProvider>
    </html>
  );
}
